########################################################################################
#                                                                                      #
#      WAVIN AHC-9000 FLOOR HEATING CONTROLLER SOFTWARE FOR HOME ASSISTANT             #
#                                                                                      #   
#        Code developed by : Heine Koldbro Madsen and Samuel Sieb 2021                 #
#                                                                                      #
#           https://github.com/heinekmadsen/esphome_wavinahc9000v3/tree/main           #    
#                                                                                      #
# Hardware by : Mogens Groth Nicolaisen https://github.com/nic6911/Wavin-AHC-9000-mqtt #
#                                                                                      #
########################################################################################
 
esphome:
  name: wavin

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

external_components:
  - source: github://heinekmadsen/esphome_wavinahc9000v3
    components: [wavin_ahc9000]
    refresh: 0s

logger:
  baud_rate: 0

uart:
  id: uart_wavin
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 38400
  stop_bits: 1
  parity: NONE
  rx_buffer_size: 1024

wavin_ahc9000:
  id: wavin
  uart_id: uart_wavin
  update_interval: 15s
  allow_mode_writes: false
  poll_channels_per_cycle: 1
  flow_control_pin: GPIO10


  channel_01_friendly_name: "Bedroom"
  channel_02_friendly_name: "Living Room"
  channel_03_friendly_name: "Kitchen"

climate:
  # Group climates (auto-generated names may differ; you can rename here)
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Living Room & Kitchen"  # from channels 2 & 3
    members: [2,3]
  # Single channel climates (channel 1)
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Bedroom"
    channel: 1
  # (Channels 2 & 3 single climates were commented out in suggestion because they are grouped)

sensor:
  # Battery & temperature sensors (optional; include only what you need)
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Bedroom Battery"
    channel: 1
    type: battery
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Bedroom Temperature"
    channel: 1
    type: temperature
  # Add more sensors per channel/group as required

api:

wifi:
  ssid: "<your-ssid>"
  password: "<your-password>"
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wavin Fallback Hotspot"
    password: ""

ota:
  platform: esphome
